# Generated by Django 4.1.1 on 2022-09-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('stat', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
